In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.3.1'

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [4]:
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [5]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2]= le.fit_transform(X[:,2])

In [7]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[
    ('oh' , OneHotEncoder(), [1])
], remainder='passthrough')

X = np.array(ct.fit_transform(X))

In [8]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [9]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y , test_size = 0.2, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler

st = StandardScaler()
X_train = st.fit_transform(X_train)
X_test = st.transform(X_test)

In [11]:
ann = tf.keras.models.Sequential()

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

In [14]:
ann.add(tf.keras.layers.Dense(units=1, activation = 'sigmoid'))

In [15]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy' ,metrics =['accuracy'] )

In [16]:
ann.fit(X_train,y_train,batch_size=32,epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5340 - accuracy: 0.7893
Epoch 2/100
250/250 [==============================] - 0s 868us/step - loss: 0.4784 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 816us/step - loss: 0.4551 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 848us/step - loss: 0.4423 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 832us/step - loss: 0.4348 - accuracy: 0.7964
Epoch 6/100
250/250 [==============================] - 0s 856us/step - loss: 0.4300 - accuracy: 0.8031
Epoch 7/100
250/250 [==============================] - 0s 832us/step - loss: 0.4260 - accuracy: 0.8096
Epoch 8/100
250/250 [==============================] - 0s 832us/step - loss: 0.4221 - accuracy: 0.8151
Epoch 9/100
250/250 [==============================] - 0s 852us/step - loss: 0.4192 - accuracy: 0.8194
Epoch 10/100
250/250 [==============================] - 0s 900us/step - los

250/250 [==============================] - 0s 852us/step - loss: 0.3361 - accuracy: 0.8621
Epoch 80/100
250/250 [==============================] - 0s 828us/step - loss: 0.3356 - accuracy: 0.8634
Epoch 81/100
250/250 [==============================] - 0s 880us/step - loss: 0.3361 - accuracy: 0.8622
Epoch 82/100
250/250 [==============================] - 0s 880us/step - loss: 0.3354 - accuracy: 0.8639
Epoch 83/100
250/250 [==============================] - 0s 872us/step - loss: 0.3356 - accuracy: 0.8634
Epoch 84/100
250/250 [==============================] - 0s 800us/step - loss: 0.3354 - accuracy: 0.8637
Epoch 85/100
250/250 [==============================] - 0s 848us/step - loss: 0.3353 - accuracy: 0.8616
Epoch 86/100
250/250 [==============================] - 0s 836us/step - loss: 0.3350 - accuracy: 0.8635
Epoch 87/100
250/250 [==============================] - 0s 804us/step - loss: 0.3351 - accuracy: 0.8629
Epoch 88/100
250/250 [==============================] - 0s 868us/step - loss:

In [19]:
X_train[0]
X[0]

array([1.0, 0.0, 0.0, 619, 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [25]:
ann.predict(st.transform([[1,0,0,600,1,42,3,60000,2,1,1,50000]])) > 0.5

array([[False]])

In [38]:
y_pred = ann.predict(X_test)
y_pred = (y_pred>0.5)

In [39]:
print(np.concatenate(
            (
                y_pred.reshape(len(y_pred),1),
                y_test.reshape(len(y_test),1)
            )
            ,1
        )
     )

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]
