In [1]:
import numpy as np
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)

In [2]:
X_b = np.c_[np.ones((100, 1)), X] # add x0 = 1 to each instance
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

In [3]:
X_b

array([[1.        , 1.8711195 ],
       [1.        , 0.42240601],
       [1.        , 1.066374  ],
       [1.        , 0.34877221],
       [1.        , 1.8499472 ],
       [1.        , 1.51796083],
       [1.        , 0.8242564 ],
       [1.        , 0.69712165],
       [1.        , 0.98987632],
       [1.        , 0.52770457],
       [1.        , 1.51457701],
       [1.        , 1.33751996],
       [1.        , 0.37189997],
       [1.        , 0.44966195],
       [1.        , 1.94029787],
       [1.        , 0.13478372],
       [1.        , 1.27309176],
       [1.        , 1.78974926],
       [1.        , 1.84945396],
       [1.        , 0.26205262],
       [1.        , 1.02477151],
       [1.        , 1.87235798],
       [1.        , 0.4321508 ],
       [1.        , 0.92575799],
       [1.        , 0.84445245],
       [1.        , 1.4591142 ],
       [1.        , 1.0725718 ],
       [1.        , 1.8450646 ],
       [1.        , 1.23035026],
       [1.        , 0.53925325],
       [1.

# Batch Gradient Descent

In [4]:
m=100
n_epochs = 50
t0, t1 = 5, 50 # learning schedule hyperparameters
def learning_schedule(t):
    return t0 / (t + t1)
theta = np.random.randn(2,1) # random initialization
count_batch=0
for epoch in range(n_epochs):
    for i in range(m):
        g = 2/m * X_b.T.dot(X_b.dot(theta) - y)
        eta = learning_schedule(epoch * m + i)
        theta = theta - (eta * g)
        count_batch+=1

In [5]:
print(theta,count_batch)

[[3.85002749]
 [3.01670522]] 5000


In [6]:
m=100
n_epochs = 50
t0, t1 = 5, 50 # learning schedule hyperparameters
def learning_schedule(t):
    return t0 / (t + t1)
theta1 = np.random.randn(2,1) # random initialization
count_stochastic=0
for epoch in range(n_epochs):
    for i in range(m):
        random_index = np.random.randint(m)
        xi = X_b[random_index:random_index+1]
        yi = y[random_index:random_index+1]
        gradients = 2 * xi.T.dot(xi.dot(theta1) - yi)
        eta = learning_schedule(epoch * m + i)
        theta1 = theta1 - eta * gradients
        count_stochastic+=1

In [7]:
print(theta1,count_stochastic)

[[3.87022012]
 [3.05189872]] 5000


In [8]:
X_b.shape

(100, 2)